// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pizzeria;

#nullable disable

namespace Pizzeria.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250112183119_UpdateMedewerkerFunctieRelation")]
    partial class UpdateMedewerkerFunctieRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Pizzeria.Model.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gebruikersnaam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GehashteWachtwoord")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActief")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Wachtwoord")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Pizzeria.Model.Functie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Functies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naam = "Manager"
                        },
                        new
                        {
                            Id = 2,
                            Naam = "Bakker"
                        },
                        new
                        {
                            Id = 3,
                            Naam = "Bezorger"
                        });
                });

            modelBuilder.Entity("Pizzeria.Model.Medewerker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FunctieId")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Wachtwoord")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FunctieId");

                    b.ToTable("Medewerkers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "trump123@gmail.com",
                            FunctieId = 1,
                            Naam = "Trump123",
                            Wachtwoord = "EBc1oatbEj8XsCqLny1mLO46DW0IFgeB3fE0atZ2QjM="
                        },
                        new
                        {
                            Id = 2,
                            Email = "bakker123@gmail.com",
                            FunctieId = 2,
                            Naam = "Bakker123",
                            Wachtwoord = "SJFbA3wyTJQwuGoUudRvOPsle5IGSdTtUsGFvQ/pxV8="
                        },
                        new
                        {
                            Id = 3,
                            Email = "bezorger123@gmail.com",
                            FunctieId = 3,
                            Naam = "Bezorger123",
                            Wachtwoord = "Dqhkdz4yNIfSocJchTc46F4jrcYHyZz4iPpcZknsGGg="
                        });
                });

            modelBuilder.Entity("Pizzeria.Model.Medewerker", b =>
                {
                    b.HasOne("Pizzeria.Model.Functie", "Functie")
                        .WithMany()
                        .HasForeignKey("FunctieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Functie");
                });
#pragma warning restore 612, 618
        }
    }
}
